package rules;
import com.zlj.drools.domain.Person;
import java.util.Date
import java.util.Calendar;

rule "checkAge"
    when
        $p:Person(age != getBirthday(birthday));
    then
        System.out.println($p.getName() + "的年龄错误。");
        $p.setAge(getAgeByBirthday($p.getBirthday()));
end

function int getAgeByBirthday(Date birthday){
    int age = 0;
    Calendar now = Calendar.getInstance();
    now.setTime(new Date());

    Calendar birth = Calendar.getInstance();
    birth.setTime(birthday);

    if(!birth.after(now)){
        age = now.get(Calendar.YEAR) - birth.get(Calendar.YEAR);
        if (now.get(Calendar.DAY_OF_YEAR) > birth.get(Calendar.YEAR)){
            age += 1;
        }
    }
    return age;
}